config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "my_cards", to: "credit_cards#my_cards"

  resources :credit_cards do
    resources :reservations, only: %i[new create]
  end

  patch "/reservations/:id/accept", to: "reservations#accept", as: :accept
  patch "/reservations/:id/reject", to: "reservations#reject", as: :reject
  resources :reservations, only: %i[show destroy edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  ISSUERS = ["BMO", "Scotiabank", "Bank of America", "Swiss", "Credit Union", "TD", "Desjardins"].freeze
  CARD_TYPE = ["Costco", "Triangle", "VISA", "Mastercard", "AMEX", "Discover"].freeze

  belongs_to :user
  has_many :reservations, dependent: :destroy
  validates :number, presence: true
  validates :pin, presence: true
  validates :date, presence: true
  validates :card_type, presence: true
  validates :card_issuer, presence: true
  validates :credit_limit, presence: true
  validates :credit_limit, comparison: { greater_than: 0 }
  validates :address, presence: true
  validates :price_per_day, presence: true
  validates :price_per_day, comparison: { greater_than: 0 }
  validates :cardholder, presence: true
  validates :card_type, inclusion: { in: CARD_TYPE }
  validates :card_issuer, inclusion: { in: ISSUERS }
  validates :credit_limit, length: { in: 3..10 }
  validates :price_per_day, length: { in: 1..5 }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :credit_card
  belongs_to :user
  validates :end_date, comparison: { greater_than: :start_date }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations
  has_many :credit_card, dependent: :destroy
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :set_cc, only: %i[show update destroy edit]

  def index
    if params[:type].present?
      @credit_cards = CreditCard.where(card_type: params[:type])
      @type = "<span class='bg-info'>#{params[:type]}</span> "
    else
      @credit_cards = CreditCard.all
    end
  end

  def my_cards
    @credit_cards = CreditCard.select { |card| card.user_id == current_user.id }
  end

  def show
    @reservation = Reservation.new
    @reservations = Reservation.all
    @reservations = @reservations.select { |reservation| reservation.credit_card_id == @credit_card.id }

    @marker =
      {
        lat: @credit_card.latitude,
        lng: @credit_card.longitude
      }
  end

  def new
    @credit_card = CreditCard.new
    @credit_card.user_id = current_user.id
  end

  def create
    @credit_card = CreditCard.new(credit_card_params)
    @credit_card.user = current_user
    if @credit_card.save
      redirect_to my_cards_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @credit_card.update(credit_card_params)
    redirect_to credit_card_path(@credit_card)
  end

  def destroy
    if @credit_card.user_id == current_user.id
      @credit_card.destroy
      redirect_to credit_cards_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_cc
    @credit_card = CreditCard.find(params[:id])
  end

  def credit_card_params
    params.require(:credit_card).permit(:number, :pin, :cardholder, :card_type,
    :card_issuer, :credit_limit, :address, :date, :price_per_day)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @credit_cards = CreditCard.last(6)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_credit_card, only: %i[new create]
  before_action :set_reservation, only: %i[destroy edit update accept reject]

  def show
    @reservations_all = Reservation.all
    @reservations = @reservations_all.select { |reservation| reservation.user_id == current_user.id }
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservations_params)
    @reservation.credit_card = @credit_card
    @reservation.user = current_user
    if @reservation.save
      redirect_to credit_card_path(@credit_card)
    else
      render "credit_cards/show", status: :unprocessable_entity
    end
  end

  def destroy
    @reservation.destroy
    redirect_to credit_card_path(@reservation.credit_card_id)
  end

  def edit
  end

  def update
    @credit_card = CreditCard.find(@reservation.credit_card_id)
    @reservation.update(reservations_params)
    @reservation.status = "pending" if @credit_card.user_id != current_user.id
    redirect_to credit_card_path(@reservation.credit_card_id)
  end

  def accept
    @reservation.update(status: "accepted")
    redirect_to credit_card_path(@reservation.credit_card_id)
  end

  def reject
    @reservation.update(status: "rejected")
    redirect_to credit_card_path(@reservation.credit_card_id)
  end

  private

  def set_credit_card
    @credit_card = CreditCard.find(params[:credit_card_id])
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def reservations_params
    params.require(:reservation).permit(:start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/credit_cards/_button.html.erb
<%= link_to "Start now", "#", class: "btn btn-gradient" %>

app/views/credit_cards/_card.html.erb
<div class="card-product">
  <%= link_to credit_card_path(card), :action => 'go' do %>
    <div class="image-overlay"><%= image_tag "#{card.card_type}.jpg", alt: "Card type" %></div>
    <div class="card-product-infos">
      <div class="d-flex align-items-center">
        <div>
          <p><strong>Card Issuer:</strong> <%=card.card_issuer%></p>
          <p><strong>Credit Limit: </strong>$<%= card.credit_limit %></p>
        </div>
        <div class="pricing text-center">
          <small>You pay:</small>
          <p><strong>$<%= card.price_per_day %></strong></p>
          <small>per day</small>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/credit_cards/_card_home_page.erb
<div class="credit-card">
  <img src="https://www.costco.ca/wcsstore/CostcoCABCCatalogAssetStore/feature-pages/17w1217-membership-card-executive.png" />
  <div class="card-trip-infos">
    <div>
      <h2>Costco Card</h2>
      <p>Make your trips to Costco worth it!</p>
    </div>
    <h2 class="card-trip-pricing">$50</h2>
  </div>
</div>

app/views/credit_cards/_form.html.erb
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-10">
      <div class="p-4 shadow-lg border">
        <%= simple_form_for(credit_card) do |f| %>
          <div class="row">
            <div class= "col">
              <%= f.input :cardholder,  input_html: { class: 'form-control' } %>
            </div>
            <div class= "col">
              <%= f.input :address %>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <%= f.input :card_type, collection: CreditCard::CARD_TYPE %>
            </div>
            <div class="col">
              <%= f.input :card_issuer, collection: CreditCard::ISSUERS %>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <%= f.input :number %>
            </div>
            <div class="col">
              <%= f.input :date %>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <%= f.input :pin %>
            </div>
            <div class="col">
              <%= f.input :credit_limit %>
            </div>
          </div>
          <%= f.input :price_per_day %>
          <%= f.submit class: "btn btn-primary" %>
          <%= link_to "Cancel", credit_cards_path, class: "btn btn-outline-secondary my-3" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/credit_cards/edit.html.erb
<div class="container py-4">
  <h3 class="text-center">Update Credit Card Information</h3>
  <% if user_signed_in? %>
    <%= render "form", credit_card: @credit_card %>
    <% @credit_card.user_id = current_user.id %>
  <% end %>
</div>

app/views/credit_cards/index.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-8">
      <h2>Here are all the <%= raw(@type) %>credit cards at your disposal</h2>
      <div class="filters">
        <% if @type %>
          <div class="mt-4">
            <%= link_to "Clear filter", credit_cards_path %>
          </div>
        <% else %>
          <div class="mt-4">
            <%= "Filter by card type:" %>
            <% CreditCard::CARD_TYPE.each do |card| %>
              <a href="/credit_cards?type=<%= card %>" class="btn btn-outline-primary"><%= card %></a>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="row py-4">
        <% @credit_cards.each do |card| %>
          <div class="col-12 col-xl-6 mb-4">
            <%= render "card", card: card %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-md-4">
      <div class="mid-gray p-4 h-100">
        <div class="sticky-buttons">
          <%= link_to raw('<i class="fa-solid fa-plus"></i> Add credit card'), new_credit_card_path, class: "btn d-block btn-primary btn-lg mb-4" %>
          <%= link_to raw('<i class="fa-solid fa-address-card"></i> My reservations'), reservation_path(current_user), class: "btn d-block btn-primary btn-lg mb-4" %>
          <%= link_to raw('<i class="fa-solid fa-credit-card"></i> My cards'), my_cards_path, class: "btn d-block btn-primary btn-lg mb-4" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/credit_cards/my_cards.html.erb
<div class="container py-5">
  <h3 class="text-center">Your cards: </h3>
  <div class="row pt-4">
    <% @credit_cards.each do |card| %>
      <div class="col-12 col-md-6 col-xl-4 mb-4">
        <%= render "card", card: card %>
      </div>
    <% end %>
  </div>
</div>

app/views/credit_cards/new.html.erb
<div class="container py-4">
  <h3 class="text-center">Please enter your credit card information</h3>
  <% if user_signed_in? %>
    <%= render "form", credit_card: @credit_card %>
    <% @credit_card.user_id = current_user.id %>
  <% end %>
</div>

app/views/credit_cards/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(<%= asset_path "#{@credit_card.card_type}.jpg" %>);"></div>
<div class="container py-4">
  <div class="row">
    <div class="col-12 col-md-8">
      <h2>Here is <%= @credit_card.cardholder %>'s card</h2>
      <h3 class="text-primary">$<%= @credit_card.price_per_day %> per day</h3>

      <div data-controller="map"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY']%>"
        data-map-marker-value="<%= @marker.to_json %>"
        style="width: 100%; height: 500px"></div>

      <hr class="my-5">

      <% if @credit_card.user_id == current_user.id && @reservations&.any? %>
        <h3>Your card is reserved:</h3>
      <% elsif @reservations&.any? %>
        <h3>This card is reserved: </h3>
      <% end %>
      <% @reservations&.each do |reservation| %>
        <div class= "py-4">
          <div class="d-flex justify-content-between">
            <% if reservation.status == "pending" %>
              <span class="badge rounded-pill text-bg-info my-2"><%= reservation.status %></span>
            <% elsif reservation.status == "accepted" %>
              <span class="badge rounded-pill text-bg-success my-2"><%= reservation.status %></span>
            <% else %>
              <span class="badge rounded-pill text-bg-danger my-2"><%= reservation.status %></span>
            <% end %>
            <% if @credit_card.user_id == current_user.id %>
              <p><%= link_to "Accept", accept_path(reservation), data: { turbo_method: :patch}%> | <%= link_to "Reject", reject_path(reservation), data: { turbo_method: :patch}%></p>
            <% end %>
          </div>
          <div class="list-group mb-4">
            <span class="list-group-item"><strong>By:</strong> <%= reservation.user.email %></span>
            <span class="list-group-item"><strong>From:</strong> <%= reservation.start_date %></span>
            <span class="list-group-item"><strong>Until:</strong> <%= reservation.end_date %></span>
          </div>
          <% if reservation.user_id == current_user.id %>
            <p>
              <%= link_to raw('<i class="fa-solid fa-pen-to-square"></i> Edit reservation'), edit_reservation_path(reservation), class: "btn btn-primary" %>
              <%= link_to raw('<i class="fa-solid fa-trash"></i> Cancel reservation'), reservation_path(reservation), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-primary" %>
            </p>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="col-12 col-md-4">
      <div class="mid-gray p-4 h-100">
        <h5 class="mb-3"><strong>Card Type: </strong><%= @credit_card.card_type %></h5>
        <h5 class="mb-3"><strong>Card Issuer: </strong><%= @credit_card.card_issuer %></h5>
        <h5 class="mb-3"><strong>Credit Limit: </strong>$<%= @credit_card.credit_limit %></h5>
        <% if @credit_card.user_id == current_user.id %>
        <%= link_to raw('<i class="fa-solid fa-trash"></i> Remove credit card'), credit_card_path(@credit_card), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn d-block btn-primary btn-lg mb-4" %>
        <%= link_to raw('<i class="fa-solid fa-pen-to-square"></i> Edit credit card'), edit_credit_card_path, class: "btn d-block btn-primary btn-lg mb-4" %>
      <% else %>
        <button type="button" class="btn d-block btn-primary btn-lg mb-4 w-100" data-bs-toggle="modal" data-bs-target="#new_reservation_modal">
          <i class="fa-solid fa-address-card"></i> Reserve credit card
        </button>
      <% end %>
      </div>
    </div>
  </div>
</div>
<%= render "reservations/modal", credit_card: @credit_card, reservation: @reservation %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Credify</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(<%= asset_path "bills.png" %>);">
  <div class="container">
    <h1><strong>Need more money to spend?</strong> <strong>We have thousands of credit cards for rent</strong></h1>
    <p>Join our scheme and Use Credify today.</p>
    <% if user_signed_in? %>
      <%= link_to "Find a card", credit_cards_path, class: "btn btn-gradient btn-light-blue" %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-gradient btn-light-blue" %>
    <% end %>
  </div>
</div>

<div class="bg-white">
  <div class= "container py-5">
    <h2><strong>The Airbnb for Credit Cards</strong></h2>
    <div class="row">
      <% CreditCard::CARD_TYPE.each do |card_type| %>
        <div class="col-12 col-sm-6 col-lg-4 py-3">
          <div class="card-category" style="background-image: url(<%= asset_path "#{card_type}.jpg" %>);">
            <a href="/credit_cards?type=<%= card_type %>"><%= card_type %></a>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class= "container py-5">
  <h2><strong>Popular Credit Cards</strong></h2>
  <div class="row py-4">
    <% @credit_cards.each do |card| %>
      <div class="col-12 col-xl-6 mb-4">
        <%= render "credit_cards/card", card: card %>
      </div>
    <% end %>
  </div>
</div>

app/views/reservations/_modal.html.erb
<div class="modal modal-lg fade" id="new_reservation_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">When do you need this card?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
      </div>

      <%= simple_form_for([credit_card, reservation]) do |f| %>
        <div class="modal-body">
          <%= f.input :start_date %>
          <%= f.input :end_date %>
        </div>
        <div class="modal-footer">
          <%= f.submit class: "btn btn-primary" %>
          <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reservations/edit.html.erb
<div class="container py-4">
  <h3 class="text-center">Enter new dates</h3>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-10">
        <div class="p-4 shadow-lg border">
          <%= simple_form_for([@credit_card, @reservation]) do |f| %>
            <%= f.input :start_date, data: { placeholder: @reservation.start_date} %>
            <%= f.input :end_date, data: { placeholder: @reservation.end_date} %>
            <%= f.submit class: "btn btn-primary" %>
            <%= link_to "Cancel", credit_card_path(@reservation.credit_card), class: "btn btn-outline-secondary my-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="container py-4">
  <h3 class="text-center">When do you need this card?</h3>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-10">
        <div class="p-4 shadow-lg border">
          <%= simple_form_for([@credit_card, @reservation]) do |f| %>
          <%= f.input :start_date %>
          <%= f.input :end_date %>
          <%= f.submit %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="container py-4">
<h3 class="text-center">Your reservations: </h3>
<div class="row">
<% @reservations.each do |reservation| %>
  <div class="col-12 col-md-4 py-4">
    <% if reservation.status == "pending" %>
        <span class="badge rounded-pill text-bg-info my-2"><%= reservation.status %></span>
    <% elsif reservation.status == "accepted" %>
        <span class="badge rounded-pill text-bg-success my-2"><%= reservation.status %></span>
    <% else %>
        <span class="badge rounded-pill text-bg-danger my-2"><%= reservation.status %></span>
    <% end %>

    <div class="list-group mb-4">
      <h5 class="list-group-item mb-0 mid-gray"><strong>For: </strong><%= link_to "#{reservation.credit_card.cardholder}'s card",  credit_card_path(reservation.credit_card_id) %></h5>
      <span class="list-group-item"><strong>From: </strong><%= reservation.start_date %></span>
      <span class="list-group-item"><strong>Until: </strong><%= reservation.end_date %></span>
    </div>
    <%= link_to raw('<i class="fa-solid fa-pen-to-square"></i> Edit reservation'), edit_reservation_path(reservation), class: "btn btn-primary" %>
    <%= link_to raw('<i class="fa-solid fa-trash"></i> Cancel reservation'), reservation_path(reservation), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-primary" %>
  </div>
<% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/ShadowSpin1/credify"><i class="fab fa-github"></i></a>
  </div>
  <div class="footer-copyright">
    © Credify. All rights reserved.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "credify-logo.jpg", alt: "Credify", width: 200 %>
      <span class="ms-2 text-primary fw-bold">Credify</span>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Browse cards", credit_cards_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-toggle d-flex align-items-center" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.photo.key %>
                <%= cl_image_tag current_user.photo.key, crop: :thumb, class: "rounded-circle avatar" %>
              <% else %>
                <i class="fa-solid fa-circle-user fa-2xl"></i>
              <% end %>
            </div>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Add credit card", new_credit_card_path, class: "dropdown-item" %>
              <%= link_to "My reservations", reservation_path(current_user), class: "dropdown-item" %>
              <%= link_to "My cards", my_cards_path, class: "dropdown-item" %>
              <%= link_to "Edit my profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up",new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>